1. promise 接收一个立即执行函数fn
2. promise 有三个状态
3. 函数fn 有两个参数，参数分别为两个函数
4. this的问题
5. then 方法的实现，两个参数是啥
   1. 成功状态
   2. 拒绝状态
6. promise 的参数函数 fn抛出一个异常，怎么接
```js
 let promise = new myPromise((resolve, reject) => {
   throw new Error("白嫖不成功");
 });
```
7. then 方法的参数类型不对，咋整
8. 异步执行
```js
// 测试 demo1
console.log(1);
let promise1 = new myPromise((resolve, reject) => {
  console.log(2);
  resolve("这次一定");
});
promise1.then(
  (result) => {
    console.log("fulfilled:", result);
  },
  (reason) => {
    console.log("rejected:", reason);
  }
);
console.log(3);
// 测试 demo2
/**
 * 1
 * 2
 * 3
 * A pending
 * B pending
 * 4
 * C pengding
 * fulfilled 这次一定
 *
 * */
console.log(1); // 1
let promise1 = new myPromise((resolve, reject) => {
  console.log(2); // 2
  setTimeout(() => {
    // 推进 宏任务 等待执行
    console.log("A", promise1.PromiseState);
    resolve("这次一定");
    console.log("B", promise1.PromiseState);
    console.log(4);
  });
});
// promise.then()是微任务，将promise.then()加入微任务队列，等待执行
promise1.then(
  (result) => {
    console.log("C", promise1.PromiseState);
    console.log("fulfilled:", result);
  },
  (reason) => {
    console.log("rejected:", reason);
  }
);
console.log(3); // 3 执行栈已经清空
```
9. then 的链式时调用
```js
let p1 = new Promise((resolve, reject) => {
  resolve(10)
})
p1.then(res => {
  console.log('fulfilled', res);
  return 2 * res
}).then(res => {
  console.log('fulfilled', res)
})
// fulfilled 100
// fulfilled 200
```
#### then
1. then 返回一个 `promise2((resolve,reject)=>{})`，then的参数是（nFulfilled, onRejected）
2. then 的参数如果返回 一个值x，那么 x 必须执行 **Promise 解决过程 resolvePromise()**
3. then 的参数执行过程抛出异常，`promise2` 必须拒绝
4. then 的pending 状态同样进行 2，3 的处理
#### Promise 解决过程 resolvePromise(promise2,x,resolve,reject)
1. 如果`promise2 和 x` 指向同一个对象，请以 TypeError 拒绝执行 promsie
2. 如果 `x 为 Promsie2`，则用 promsie 接受 x 的状态 (如下解释)
  - x 状态是 pending，promise 需保持为等待态直至 x 被执行或拒绝。也就是x 被执行x，如果执行的时候拿到一个y，还要继续解析y。
  ```js
  x.then(
    y => {
      resolvePromise(promise2, y, resolve, reject)
    }, 
    reject
  )
  ```
  - x 状态是 fulfilled，用 promise2 的 resolve 处理x的结果
  - x 状态是 rejectd，用 promise2 的 reject 处理x的结果
3. x 为对象或者函数
  1. 把 `x 的 then（x.then）` 赋值给一个 新的 `then2` 变量
  2. 如果 1 报错那么抛出异常
  3. 如果`then2` 是方法，那么 `以 x 为上下文执行 then2`
  ```js
  then2.call(x, y=>{
    resolvePromise(promise2, y, resolve, reject);
  }, r => {
    reject(r)
  })
  ```
  4. 给 then2 添加异常处理
  ```js
  try {
    then2.call(
      x,
      (y) => {
        resolvePromise(promise2, y, resolve, reject);
      },
      (r) => {
        reject(r);
      }
    );
  } catch (e) {
    reject(e);
  }
  ```
  5. 如果 resolvePromise 和 rejectPromise 均被调用，或者被同一参数调用了多次，则优先采用首次调用并忽略剩下的调用, 避免多次调用

  ```js
  let called = false;
  try {
    then2.call(
      x,
      (y) => {
        if (called) return;
        called = true;
        resolvePromise(promise2, y, resolve, reject);
      },
      (r) => {
        if (called) return;
        called = true;
        reject(r);
      }
    );
  } catch (e) {
    if (called) return;
    called = true;
    reject(e);
  }
  ```
  6. then2 不是函数，以 x 为参数执行 promise。 `resolve(x)`
4. x 不为对象或者函数 `return resolve(x)`;